baseURL = "https://glsngr.xyz/"
title = "glsngr"
theme = "ananke"          # or another theme; remove if you go themeless
languageCode = "en-us"

[pagination]
  pagerSize = 10

[params]
  description = "My portfolio + dev blog"
  github = "https://github.com/mgelsinger"
  youtube = "https://github.com/mgelsinger"

[menu]
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 10
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 20
