baseURL = "https://glsngr.xyz/"
title = "Home"
theme = "hugo-theme-stack"
languageCode = "en-us"

[pagination]
  pagerSize = 10

[params]
  description = "My portfolio + dev blog"
  github = "https://github.com/mgelsinger"
  youtube = "https://github.com/mgelsinger"
  mainSections = ["posts"]
  featuredImageField = "image"

  [params.colorScheme]
    toggle = true
    default = "dark"

  [params.sidebar]
    
    [params.sidebar.avatar]
      enabled = true
      local = true
      src = "img/avatar.jpg"

[menu]
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 20
