name: Deploy Hugo to S3 + CloudFront

on:
  push:
    branches: [ main ]   # change if your default branch isn't main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  S3_BUCKET: arn:aws:s3:::glsngr.xyz
  CF_DISTRIBUTION_ID: E3R94LH2BR4JE3
  ROLE_ARN: arn:aws:iam::761341390501:role/GitHubActionsDeployRole

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: hugo-deploy
      cancel-in-progress: true

    steps:
      - name: Checkout (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive   # <-- pulls your Hugo theme if it's a Git submodule

      - name: Setup Hugo (extended)
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build site
        run: hugo --minify

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ env.ROLE_ARN }}

      - name: Sync to S3 (mirror)
        run: aws s3 sync public/ "s3://${{ env.S3_BUCKET }}/" --delete

      - name: Invalidate CloudFront
        run: aws cloudfront create-invalidation --distribution-id "${{ env.CF_DISTRIBUTION_ID }}" --paths "/*"
